config/routes.rb
Rails.application.routes.draw do

  resources :current_accounts
  resources :lower_receivables, only: [:destroy]
  resources :account_receivables do 
    member do
      get 'lower'
      post 'pay'
    end    
  end

  resources :account_payables
  resources :cash_accounts
  resources :banks
  resources :payment_methods
  resources :cost_centers
  resources :drivers

  devise_for :users, :class_name => 'User'
  root to: "static_pages#home"

end

app/models/current_account.rb
class CurrentAccount < ActiveRecord::Base
  validates :cash_account_id, presence: true
  validates :data, presence: true
  validates :valor, presence: true
  validates :tipo, presence: true
  validates :historico, presence: true

  belongs_to :cash_account
  belongs_to :cost_center
  #has_many :account_receivables

  module TipoLancamento
    CREDITO = 1
    DEBITO  = -1
  end
  
  def credito_debito
  	case self.tipo
  		when -1 then "Débito"
  		when  1	then "Crédito"
  		else ""
  	end
  end
end

app/controllers/current_accounts_controller.rb
class CurrentAccountsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_current_account, only: [:show, :edit, :update, :destroy]

  # GET /current_accounts
  # GET /current_accounts.json
  def index
    @current_accounts = CurrentAccount.all
  end

  # GET /current_accounts/1
  # GET /current_accounts/1.json
  def show
  end

  # GET /current_accounts/new
  def new
    @current_account = CurrentAccount.new
  end

  # GET /current_accounts/1/edit
  def edit
  end

  # POST /current_accounts
  # POST /current_accounts.json
  def create
    @current_account = CurrentAccount.new(current_account_params)

    respond_to do |format|
      if @current_account.save
        format.html { redirect_to @current_account, notice: 'Current account was successfully created.' }
        format.json { render :show, status: :created, location: @current_account }
      else
        format.html { render :new }
        format.json { render json: @current_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /current_accounts/1
  # PATCH/PUT /current_accounts/1.json
  def update
    respond_to do |format|
      if @current_account.update(current_account_params)
        format.html { redirect_to @current_account, notice: 'Current account was successfully updated.' }
        format.json { render :show, status: :ok, location: @current_account }
      else
        format.html { render :edit }
        format.json { render json: @current_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /current_accounts/1
  # DELETE /current_accounts/1.json
  def destroy
    @current_account.destroy
    respond_to do |format|
      format.html { redirect_to current_accounts_url, notice: 'Current account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_current_account
      @current_account = CurrentAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def current_account_params
      params.require(:current_account).permit(:cash_account_id, :cost_center_id, :tipo, :data, :valor, :historico)
    end
end

app/helpers/current_accounts_helper.rb
module CurrentAccountsHelper
end

app/views/current_accounts/_form.html.erb
<%= form_for(@current_account) do |f| %>
  <% if @current_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@current_account.errors.count, "error") %> prohibited this current_account from being saved:</h2>

      <ul>
      <% @current_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :cash_account_id %><br>
    <%= f.select(:cash_account_id, CashAccount.order(:name).collect {|c| [c.name, c.id]}, {include_blank: true}, {class: "form-control"} ) %>
  </div>
  <div class="form-group">
    <%= f.label :cost_center_id %><br>
    <%= f.select(:cost_center_id, CostCenter.order(:name).collect {|c| [c.name, c.id]}, {include_blank: true}, {class: "form-control"} ) %>
  </div>
  <div class="form-group">
    <%= f.label :tipo %><br>
    <%= f.select( :tipo, select_credito_debito, {include_blank: "Selecione Crédito/Débito"}, {class: "form-control"} ) %>      
  </div>
  <div class="form-group">
    <%= f.label :data %><br>
    <%= f.date_select :data, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :valor %><br>
    <%= f.text_field :valor, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :historico %><br>
    <%= f.text_field :historico, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Salvar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/current_accounts/edit.html.erb
<h1>Editing Current Account</h1>

<%= render 'form' %>

app/views/current_accounts/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Listing Current Accounts</div>
  <div class="panel-body">
    <%= link_to 'New Current account', new_current_account_path , class: "btn btn-primary btn-lg btn-block" %>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Cash account</th>
            <th>Cost center</th>
            <th>Tipo</th>
            <th>Data</th>
            <th>Valor</th>
            <th>Historico</th>
            <th colspan="3">Options</th>
          </tr>
        </thead>

        <tbody>
          <% @current_accounts.each do |current_account| %>
            <tr>
              <td><%= current_account.cash_account.name %></td>
              <td><%= current_account.cost_center.name %></td>
              <td><%= current_account.credito_debito %></td>
              <td><%= date_br(current_account.data) %></td>
              <td><%= current_account.valor %></td>
              <td><%= current_account.historico %></td>
              <td><%= link_to 'Show', current_account, class: "btn btn-info btn-xs" %></td>
              <td><%= link_to 'Edit', edit_current_account_path(current_account), class: "btn btn-primary btn-xs" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/current_accounts/new.html.erb
<h1>New Current Account</h1>

<%= render 'form' %>

app/views/current_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Conta:</strong>
  <%= @current_account.cash_account.name %> | 
  <strong>Saldo:</strong>
  <%= number_to_currency(@current_account.cash_account.saldo, unit: "R$ ", separator: ",", delimiter: ".") %> 
</p>

<p>
  <strong>Cost center:</strong>
  <%= @current_account.cost_center.name %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @current_account.credito_debito %>
</p>

<p>
  <strong>Data:</strong>
  <%= date_br(@current_account.data)  %>
</p>

<p>
  <strong>Valor:</strong>
  <%= number_to_currency(@current_account.valor, unit: "R$ ", separator: ",", delimiter: ".")  %>
</p>

<p>
  <strong>Historico:</strong>
  <%= @current_account.historico %>
</p>

<div class="form-group">
  <%= link_to 'Edit', edit_current_account_path(@current_account), class: "btn btn-primary" %>
  <%= link_to 'Back', current_accounts_path, class: "btn btn-default" %>
</div>