config/routes.rb
Rails.application.routes.draw do

  resources :current_accounts
  resources :lower_receivables, only: [:destroy]
  resources :account_receivables do 
    member do
      get 'lower'
      post 'pay'
    end    
  end

  resources :account_payables
  resources :cash_accounts
  resources :banks
  resources :payment_methods
  resources :cost_centers
  resources :drivers

  devise_for :users, :class_name => 'User'
  root to: "static_pages#home"

end

app/models/account_payable.rb
class AccountPayable < ActiveRecord::Base
  belongs_to :payment_method
end

app/controllers/account_payables_controller.rb
class AccountPayablesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_account_payable, only: [:show, :edit, :update, :destroy]

  # GET /account_payables
  # GET /account_payables.json
  def index
    @account_payables = AccountPayable.all
  end

  # GET /account_payables/1
  # GET /account_payables/1.json
  def show
  end

  # GET /account_payables/new
  def new
    @account_payable = AccountPayable.new
  end

  # GET /account_payables/1/edit
  def edit
  end

  # POST /account_payables
  # POST /account_payables.json
  def create
    @account_payable = AccountPayable.new(account_payable_params)

    respond_to do |format|
      if @account_payable.save
        format.html { redirect_to @account_payable, notice: 'Account payable was successfully created.' }
        format.json { render :show, status: :created, location: @account_payable }
      else
        format.html { render :new }
        format.json { render json: @account_payable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account_payables/1
  # PATCH/PUT /account_payables/1.json
  def update
    respond_to do |format|
      if @account_payable.update(account_payable_params)
        format.html { redirect_to @account_payable, notice: 'Account payable was successfully updated.' }
        format.json { render :show, status: :ok, location: @account_payable }
      else
        format.html { render :edit }
        format.json { render json: @account_payable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account_payables/1
  # DELETE /account_payables/1.json
  def destroy
    @account_payable.destroy
    respond_to do |format|
      format.html { redirect_to account_payables_url, notice: 'Account payable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account_payable
      @account_payable = AccountPayable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_payable_params
      params.require(:account_payable).permit(:type_account, :supplier_id, :cost_center_id, :payment_method_id, :documento, :data_vencimento, :valor, :observacao)
    end
end

app/helpers/account_payables_helper.rb
module AccountPayablesHelper
end

app/views/account_payables/_form.html.erb
<%= form_for(@account_payable) do |f| %>
  <% if @account_payable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account_payable.errors.count, "error") %> prohibited this account_payable from being saved:</h2>

      <ul>
      <% @account_payable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :type_account %><br>
    <%= f.number_form-group :type_account %>
  </div>
  <div class="form-group">
    <%= f.label :supplier_id %><br>
    <%= f.number_form-group :supplier_id %>
  </div>
  <div class="form-group">
    <%= f.label :cost_center_id %><br>
    <%= f.number_form-group :cost_center_id %>
  </div>
  <div class="form-group">
    <%= f.label :payment_method_id %><br>
    <%= f.text_form-group :payment_method_id %>
  </div>
  <div class="form-group">
    <%= f.label :documento %><br>
    <%= f.text_form-group :documento %>
  </div>
  <div class="form-group">
    <%= f.label :data_vencimento %><br>
    <%= f.date_select :data_vencimento %>
  </div>
  <div class="form-group">
    <%= f.label :valor %><br>
    <%= f.text_form-group :valor %>
  </div>
  <div class="form-group">
    <%= f.label :observacao %><br>
    <%= f.text_area :observacao %>
  </div>
  <div class="actions">
    <%= f.submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/account_payables/edit.html.erb
<h1>Editing Account Payable</h1>

<%= render 'form' %>

<%= link_to 'Show', @account_payable %> |
<%= link_to 'Back', account_payables_path %>

app/views/account_payables/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Listagem de Contas a Pagar</div>
  <div class="panel-body">
    <%= link_to 'Novo Pagamento', new_account_payable_path, class: "btn btn-primary btn-lg btn-block" %>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Supplier</th>
            <th>Cost center</th>
            <th>Payment method</th>
            <th>Documento</th>
            <th>Data vencimento</th>
            <th>Valor</th>
            <th>Observacao</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @account_payables.each do |account_payable| %>
            <tr>
              <td><%= account_payable.supplier_id %></td>
              <td><%= account_payable.cost_center_id %></td>
              <td><%= account_payable.payment_method %></td>
              <td><%= account_payable.documento %></td>
              <td><%= account_payable.data_vencimento %></td>
              <td><%= account_payable.valor %></td>
              <td><%= account_payable.observacao %></td>
              <td><%= link_to 'Show', account_payable %></td>
              <td><%= link_to 'Edit', edit_account_payable_path(account_payable) %></td>
              <td><%= link_to 'Destroy', account_payable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/account_payables/new.html.erb
<h1>New Account Payable</h1>

<%= render 'form' %>

<%= link_to 'Back', account_payables_path %>

app/views/account_payables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type account:</strong>
  <%= @account_payable.type_account %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @account_payable.supplier_id %>
</p>

<p>
  <strong>Cost center:</strong>
  <%= @account_payable.cost_center_id %>
</p>

<p>
  <strong>Payment method:</strong>
  <%= @account_payable.payment_method %>
</p>

<p>
  <strong>Documento:</strong>
  <%= @account_payable.documento %>
</p>

<p>
  <strong>Data vencimento:</strong>
  <%= @account_payable.data_vencimento %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @account_payable.valor %>
</p>

<p>
  <strong>Observacao:</strong>
  <%= @account_payable.observacao %>
</p>

<div class="form-group">
  <%= link_to 'Edit', edit_account_payable_path(@account_payable) %> |
  <%= link_to 'Back', account_payables_path %>
</div>